"""added address to company

Revision ID: 76f6f2b5417f
Revises: 7ec3f6e1a9b9
Create Date: 2024-05-01 16:37:29.842856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '76f6f2b5417f'
down_revision: Union[str, None] = '7ec3f6e1a9b9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('address', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'address')
    # ### end Alembic commands ###
