"""added company model

Revision ID: 7ec3f6e1a9b9
Revises: 
Create Date: 2024-05-01 16:33:04.975464

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ec3f6e1a9b9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # op.drop_table('employee')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('employee',
    # sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    # sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    # sa.Column('current', sa.BOOLEAN(), autoincrement=False, nullable=True),
    # sa.Column('job_title', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    # sa.PrimaryKeyConstraint('id', name='employee_pkey')
    # )
    op.drop_table('company')
    # ### end Alembic commands ###
